### ISSUE TITLE
Incomplete example

### ISSUE THREAD

**Issue by james-tn** [lostmygithubaccount/dasky#7]
Other than setting up the cluster, the examples are bad. Did not have steps to load data to Dask dataframe in a distributed cluster. For example in the demo notebook, how is df created?
Need better documentation. If you mean the data and ML examples are only for single machine, please note.
Anyway, needs example of running Data exploration and ML training in a cluster

**Comment by lostmygithubaccount** [comment]
I was waiting on `Dataset.to_dask_dataframe` to be released, which was supposed to happen by now, ot fix the demo notebook - then it should work as is

**Comment by james-tn** [comment]
I am not sure if that method would be efficient for a distributed environment. Not sure if it needs to collect to the driver all data? 
Anyway, how about loading from storage using this? https://github.com/dask/adlfs
I had error running it in a cluster while had no problem in single node seeking. Will try again.

**Comment by lostmygithubaccount** [comment]
It will be efficient for a distributed environment, it has just been delayed a few times - new ETA is *next few weeks*.

I've used adlfs in the past, the major issue is it can't be used for reading public blobs like open datasets: https://github.com/dask/adlfs/issues/97

In the past I had the data hosted in my subscription and had the account key in plaintext in this repo, given that `Dataset.to_dask_dataframe` was set to release soon I decided to move away from that.

**Comment by lostmygithubaccount** [comment]
a complete (and tested!) example is now available here: https://github.com/Azure/azureml-examples/blob/main/tutorials/using-dask/2.eds-at-scale.ipynb

**Comment by lostmygithubaccount** [comment]
@james-tn fyi - closing this
